ALTER TABLE tasks ADD COLUMN IF NOT EXISTS due_time TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS scheduled_time TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS follow_up_time TEXT;
ALTER TABLE task_changes ADD COLUMN IF NOT EXISTS due_time TEXT;
ALTER TABLE task_changes ADD COLUMN IF NOT EXISTS scheduled_time TEXT;
ALTER TABLE task_changes ADD COLUMN IF NOT EXISTS follow_up_time TEXT;

ALTER TABLE habits ADD COLUMN IF NOT EXISTS time_of_day TEXT;
ALTER TABLE habit_changes ADD COLUMN IF NOT EXISTS time_of_day TEXT;
