import type { MailLabel, MailMessage } from "../types";

/**
 * Demo mailbox used for local development and as a graceful fallback when no
 * Google account is connected. All operations (archive, star, read, labels)
 * are fully functional and persisted to localStorage so the inbox feels real.
 */

export const DEMO_LABELS: MailLabel[] = [
  { id: "INBOX", name: "Inbox", system: true },
  { id: "SENT", name: "Sent", system: true },
  { id: "STARRED", name: "Starred", system: true },
  { id: "UNREAD", name: "Unread", system: true },
  { id: "TRASH", name: "Trash", system: true },
  { id: "CATEGORY_PERSONAL", name: "Personal", system: true, color: "#1a73e8", textColor: "#ffffff" },
  { id: "CATEGORY_SOCIAL", name: "Social", system: true, color: "#7b1fa2", textColor: "#ffffff" },
  { id: "CATEGORY_PROMOTIONS", name: "Promotions", system: true, color: "#e8710a", textColor: "#ffffff" },
  { id: "CATEGORY_UPDATES", name: "Updates", system: true, color: "#188038", textColor: "#ffffff" },
  { id: "Label_1", name: "Work", system: false, color: "#0b8043", textColor: "#ffffff" },
  { id: "Label_2", name: "Receipts", system: false, color: "#b0600a", textColor: "#ffffff" },
  { id: "Label_3", name: "Travel", system: false, color: "#1565c0", textColor: "#ffffff" },
];

function daysAgo(dayOffset: number, hour: number, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - dayOffset);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function msg(
  id: string,
  fromName: string,
  fromEmail: string,
  subject: string,
  snippet: string,
  body: string,
  date: string,
  labelIds: string[],
  opts: { unread?: boolean; starred?: boolean; archived?: boolean; hasAttachment?: boolean } = {},
): MailMessage {
  return {
    id,
    threadId: `t-${id}`,
    from: { name: fromName, email: fromEmail },
    to: [{ name: "You", email: "you@example.com" }],
    subject,
    snippet,
    body,
    date,
    labelIds,
    unread: opts.unread ?? false,
    starred: opts.starred ?? false,
    archived: opts.archived ?? false,
    hasAttachment: opts.hasAttachment ?? false,
  };
}
export const DEMO_MESSAGES: MailMessage[] = [
  msg("m1", "Amélie Laurent", "amelie.laurent@acmestudio.fr",
    "Re: Brand sprint — final assets handoff",
    "Hey! I've packaged the final logo set, color tokens and the icon grid…",
    "Hey Constant,\n\nI've packaged the final logo set, color tokens and the icon grid into a shared Drive folder.\n\nCould you review the dark-mode variants before Thursday's client call? The only open question is the accent color contrast on the coral buttons.\n\nIf everything looks good I'll send the invoice on Friday.\n\nThanks!\nAmélie",
    daysAgo(0, 9, 24), ["INBOX", "CATEGORY_PERSONAL", "Label_1"],
    { unread: true, starred: true }),
  msg("m2", "Linear", "notifications@linear.app",
    "PRI-128 — Inbox triage flow was moved to In Progress",
    "Constant moved PRI-128 from Backlog to In Progress…",
    "Constant moved PRI-128 from Backlog to In Progress.\n\nInbox triage flow\nConnect Gmail, support archive / star / labels, and the right-click \"add to task\" flow.\n\nView in Linear: https://linear.app/prior/issue/PRI-128",
    daysAgo(0, 8, 5), ["INBOX", "CATEGORY_UPDATES", "Label_1"],
    { unread: true }),
  msg("m3", "Figma", "team@figma.com",
    "Your weekly community digest",
    "Top plugins, new widgets and files you might like…",
    "Here's what the Figma community made this week.\n\n1. Auto-layout cheat sheets\n2. A new variable typography kit\n3. Prototyping components you can copy\n\nOpen Figma to explore.",
    daysAgo(0, 7, 41), ["INBOX", "CATEGORY_PROMOTIONS"], { unread: true }),
  msg("m4", "Vercel", "notifications@vercel.com",
    "Deployment for prior failed",
    "The build for commit 7173d4a failed to compile…",
    "The deployment for `prior` (commit 7173d4a) failed.\n\nError: Type error in `app/src/App.tsx`.\n\nFix the build and push again to redeploy.",
    daysAgo(0, 6, 12), ["INBOX", "CATEGORY_UPDATES"], { unread: true, starred: true }),
  msg("m5", "SNCF Connect", "noreply@sncf-connect.fr",
    "Your e-ticket — Paris → Lyon, Fri 26 Sep",
    "Your TGV INOUI ticket is attached. Coach 12, seat 41…",
    "Hello,\n\nYour TGV INOUI ticket is attached.\n\nParis Gare de Lyon → Lyon Part Dieu\nFriday 26 September, 08:16 → 10:12\nCoach 12, seat 41 (window)\n\nHave a good trip.",
    daysAgo(1, 19, 2), ["INBOX", "Label_3"], { hasAttachment: true }),
  msg("m6", "LinkedIn", "notifications@linkedin.com",
    "You appeared in 12 searches this week",
    "Recruiters are looking at your profile…",
    "You appeared in 12 searches this week.\n\nRecruiters viewed your profile. See who's looking and what roles they have open.",
    daysAgo(1, 11, 30), ["CATEGORY_SOCIAL"], { unread: true }),
  msg("m7", "Notion", "notify@mail.notion.so",
    "You were mentioned in \"Q4 Roadmap\"",
    "Sofia mentioned you in Q4 Roadmap: \"@Constant can you own the…\"",
    "Sofia mentioned you in \"Q4 Roadmap\":\n\n\"@Constant can you own the inbox + mail integration for the Q4 launch?\"\n\nReply in Notion to continue the thread.",
    daysAgo(2, 16, 45), ["CATEGORY_UPDATES", "Label_1"]),
  msg("m8", "Amazon", "auto-confirm@amazon.fr",
    "Your order has shipped",
    "Your package with \"Mechanical keyboard keycaps\" has shipped…",
    "Your order #402-1188294-2232347 has shipped.\n\nMechanical keyboard keycaps (set of 128)\nEstimated delivery: Monday 22 September.\n\nTrack your package in Your Orders.",
    daysAgo(2, 9, 18), ["CATEGORY_UPDATES", "Label_2"], { hasAttachment: true }),
  msg("m9", "GitHub", "noreply@github.com",
    "[prior] New release v0.3.65 published",
    "gh-Constant released v0.3.65: chore(release): v0.3.65…",
    "gh-Constant released v0.3.65.\n\nchore(release): v0.3.65\n\n—\nYou are receiving this because you are watching the repository.",
    daysAgo(3, 14, 52), ["CATEGORY_UPDATES"]),
  msg("m10", "Spotify", "no-reply@spotify.com",
    "Your September Premium receipt",
    "Thanks for your payment. Your receipt is attached…",
    "Hi,\n\nThanks for your payment of €10.99 for Spotify Premium.\nYour receipt is attached.\n\nManage your subscription in your account settings.",
    daysAgo(4, 3, 0), ["Label_2"], { hasAttachment: true }),
  msg("m11", "Mamie Claire", "claire.dubois@orange.fr",
    "Photos from the weekend 📷",
    "Coucou ! Voici les photos du dimanche en famille…",
    "Coucou !\n\nVoici les photos du dimanche en famille. Dis-moi lesquelles tu préfères pour l'album.\n\nGros bisous,\nMamie Claire",
    daysAgo(4, 18, 27), ["CATEGORY_PERSONAL"], { starred: true, hasAttachment: true }),
  msg("m12", "OpenRouter", "billing@openrouter.ai",
    "Your API usage summary",
    "You used 1.4M tokens this month. View your dashboard…",
    "Your OpenRouter usage summary is ready.\n\nThis month: 1,412,384 tokens across 6 models.\nTop model: anthropic/claude-sonnet-4.\n\nView the full breakdown in your dashboard.",
    daysAgo(5, 12, 0), ["CATEGORY_UPDATES"]),
  msg("m13", "Booking.com", "customer.service@booking.com",
    "Confirm your Lisbon stay — 2 nights left to decide",
    "Your reserved room at \"Bairro Alto Hotel\" is held until…",
    "Your reserved room at \"Bairro Alto Hotel\" is held until Friday.\n\nLisbon, 3–6 October · 2 adults · Breakfast included\n€412 total, free cancellation until 1 October.\n\nConfirm your booking to lock the price.",
    daysAgo(6, 20, 15), ["INBOX", "Label_3"]),
  msg("m14", "Marc (Freelance)", "marc.dev@proton.me",
    "Invoice #2025-041 — prior sync work",
    "Hi Constant, attached is the invoice for the offline-first…",
    "Hi Constant,\n\nAttached is invoice #2025-041 for the offline-first sync engine work, due in 14 days.\n\nTotal: €1,800\nIBAN in the PDF.\n\nThanks!\nMarc",
    daysAgo(7, 10, 33), ["Label_1", "Label_2"], { hasAttachment: true }),
  msg("m15", "Twitter / X", "info@x.com",
    "Your post is getting noticed",
    "Your post got 1,240 impressions this week…",
    "Your post got 1,240 impressions this week.\n\nSee what's resonating with your audience.",
    daysAgo(8, 15, 9), ["CATEGORY_SOCIAL"]),
  msg("m16", "You", "you@example.com",
    "Re: Brand sprint — final assets handoff",
    "Thanks Amélie! I'll review the dark-mode variants tonight…",
    "Thanks Amélie! I'll review the dark-mode variants tonight and get back to you before the call.\n\nThe coral accent should be fine — we tested it at 4.5:1.\n\nConstant",
    daysAgo(0, 10, 2), ["SENT"]),
  msg("m17", "Old Newsletter", "news@stale-service.com",
    "An archived update you already handled",
    "This one was already dealt with and archived…",
    "This newsletter was already read and archived. It lives outside the inbox but is still searchable.",
    daysAgo(12, 9, 0), ["CATEGORY_UPDATES"], { archived: true }),
  msg("m18", "Suspicious Sender", "winner@totally-real-prize.xyz",
    "You WON $1,000,000!!!",
    "Claim your prize now by sending your bank details…",
    "CONGRATULATIONS! You have been selected to receive ONE MILLION DOLLARS. Reply with your bank details to claim.",
    daysAgo(1, 4, 44), ["TRASH"], { unread: true }),
];

export const DEMO_ACCOUNT_EMAIL = "you@example.com";
